// <auto-generated />
namespace Contatos.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V001 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V001));
        
        string IMigrationMetadata.Id
        {
            get { return "201712151254057_V001"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
